nextcloud-libraries/nextcloud-upload

lib/index.ts
lib/upload.ts
lib/uploader.ts
package-lock.json
package.json
rollup.config.js
src/UploadPicker.js
src/UploadPicker.vue
tsconfig.json

Add basic UI

---

.github/workflows/l10n.yml
build/extract-l10n.js
l10n/messages.pot
lib/utils/l10n.js
package-lock.json
package.json
rollup.config.js
src/UploadPicker.vue
transifex.yml

Add paused status & translations

---

src/UploadPicker.vue

Animate progress show/hide

---

.github/workflows/node-test.yml
.gitignore
__tests__/upload.spec.ts
jest.config.js
lib/upload.ts
package.json

Add Upload testing

---

lib/components/UploadPicker.vue
lib/utils/l10n.ts

Improve ts usage in l10n.ts

---

build/extract-l10n.js
l10n/messages.pot
lib/components/UploadPicker.vue

Update time estimates wordings

---

l10n/messages.pot
lib/components/UploadPicker.vue

Add cypress data selectors 

---

lib/components/UploadPicker.vue

Fix default progress bar size

---

lib/components/UploadPicker.vue

Add queue events

---

lib/upload.ts
lib/uploader.ts
tsconfig.json

Attach the request response the Upload

---

.gitignore
lib/components/ActionIcon.vue
lib/components/UploadPicker.cy.ts
lib/components/UploadPicker.vue
package-lock.json
package.json

Add context support for newFileMenuEntries

---

lib/components/UploadPicker.cy.ts
lib/components/UploadPicker.vue
lib/index.ts
lib/uploader.ts

Improve root folder handling

---

lib/components/UploadPicker.vue

Change root depending on the usage

---

lib/components/UploadPicker.vue
package-lock.json
package.json

fix: new file menu context

---

build/extract-l10n.js
cypress/components/ConflictPicker.cy.ts
cypress/components/UploadPicker.cy.ts
cypress/support/component.ts
l10n/messages.pot
lib/components/ConflictPicker.vue
lib/components/NodesPicker.vue
lib/components/UploadPicker.vue
lib/index.ts
lib/uploader.ts
package-lock.json
package.json

feat: add ConflictPicker

---

lib/uploader.ts

Follow up of: https://github.com/nextcloud-libraries/nextcloud-upload/pull/935
Ref: https://developer.mozilla.org/en-US/docs/Web/API/File/lastModified

Divide lastModified by 1000 to have seconds

---

package.json

Bump to v1.0.0-beta.19

---

cypress/components/UploadPicker.cy.ts
lib/components/UploadPicker.vue

fix: always show menu label

---

CHANGELOG.md
package-lock.json
package.json

[Full Changelog](https://github.com/nextcloud-libraries/nextcloud-upload/compare/v1.1.0...v1.1.1)
* fix: Drop dependency on moment.js by @susnux in https://github.com/nextcloud-libraries/nextcloud-upload/pull/1155
* fix(upload): Do not read chunks into memory but just stream file chunks by @susnux in https://github.com/nextcloud-libraries/nextcloud-upload/pull/1153
* Updated development dependencies
* Updated @nextcloud/dialogs from 5.2.0 to 5.3.0

chore: Prepare 1.1.1 release

---

lib/components/UploadPicker.vue
package-lock.json
package.json

* Resolves https://github.com/nextcloud/server/issues/43728

feat: Split new-menu entries into `upload` `new` and *other*

---

lib/components/NodesPicker.vue

https://github.com/nextcloud/server/pull/45417

feat(ConflictPicker): refresh preview on etag change

---

__tests__/utils/uploader.spec.ts
lib/uploader.ts
vitest.config.ts

* Chained on #1224 
* Required for https://github.com/nextcloud/server/pull/45652
* Resolves #6 
Allow upload to public shares

feat: Implement upload on public shares using dav endpoint v2

---

lib/index.ts

fix: Adjust `isPublic` detection for uploader

---

lib/uploader.ts

Seems it works a bit better (also got a few requests)

fix(uploader): increase max concurrency to 5

---

.github/workflows/transifex-conventional-rebase.yml

For auto merge of transifex commits

chore: add transifex-conventional-rebase.yml

---

lib/uploader.ts

* Fix https://github.com/nextcloud-libraries/nextcloud-upload/pull/1245#issuecomment-2214095210

fix: Allow remote URL with protocol

---

package-lock.json
package.json

Reverts nextcloud-libraries/nextcloud-upload#1285

Revert "chore: Bump @nextcloud/paths from 2.1.0 to 2.2.0"

---

lib/uploader.ts

I currently try to trance some uploader  errors, but there is really low information available when tracing.

chore: Add more debug logging to trace errors

---

__tests__/utils/logger.spec.ts

test: silence console output when testing logger

---

__tests__/utils/conflicts-handler.spec.ts
cypress/components/ConflictPicker.cy.ts
lib/utils/conflicts.ts

* Resolves https://github.com/nextcloud-libraries/nextcloud-upload/issues/1576
* Resolves https://github.com/nextcloud-libraries/nextcloud-upload/issues/1544
Make sure we also upload non conflicting files :see_no_evil:

fix: include non conflicting files for upload

---

lib/components/ConflictPicker.vue

| Before | After |
|:---------:|:------:|
|![2025-02-28_10-04](https://github.com/user-attachments/assets/4e797d98-83df-4e19-ae05-d5873a5ef1a0)|![2025-02-28_10-04_1](https://github.com/user-attachments/assets/c3441f34-0e62-4b90-bec9-eb1e216b3712)|

fix(conflictpicker): force background on sticky header

---

lib/components/UploadPicker.vue

@susnux Thanks for watching carefully

chore(i18n): Fixes wrong syntax from #1643
