nextcloud-libraries/nextcloud-upload

- .eslintrc.json
- lib/index.ts
- lib/shims-vue.d.ts
If the variable is declared using `let` or `const` we need to initialize it explicitly before it can be accessed - even if we access it using `instanceof`.
So current *beta.9* is not usable :/
> fix: Cannot access `_uploader` before initialization

- lib/components/UploadPicker.vue
Finally solved the issue with the `@nextcloud/cypress` update:
> fix: `getUploader` should only be called when a new `UploadPicker` instance is created

- __tests__/upload.spec.ts
- cypress/components/UploadPicker.cy.ts
- lib/components/UploadPicker.vue
- lib/upload.ts
- lib/uploader.ts
1. The queue reactivity have been fixed
2. Because the reference is now kept, it means the watcher can NOT work as any array change will result in both the old and the new value to point to the same ref and have no differences
3. Therefore we now have the ability to subscribe to those uploads
> feat: add notifier to watch upload and attach the File to the Upload

- __tests__/utils/config.spec.ts
- __tests__/utils/upload.spec.ts
- lib/upload.ts
- lib/uploader.ts
- lib/utils/config.ts
- lib/utils/upload.ts
Implements https://github.com/nextcloud-libraries/nextcloud-upload/issues/924
Tested locally to work with S3 primary storage with server master
> feat: Implement support for chunking v2 API

- lib/components/UploadPicker.vue
- lib/uploader.ts
> fix: iconClass render

- lib/uploader.ts
- lib/utils/upload.ts
Currently, when you upload a file, the last modified time is not forwarded to the server, so it becomes the current time.
See https://docs.nextcloud.com/server/latest/developer_manual/client_apis/WebDAV/basic.html#request-headers
Can we merge the `destinationFile` and `headers` params?
> Set proper headers in upload requests

- __tests__/utils/upload.spec.ts
- lib/utils/upload.ts
> fix: Do not block if the filetype is unknown to the browser

- cypress/components/UploadPicker.cy.ts
- l10n/messages.pot
- lib/components/UploadPicker.vue
As discussed in chat with @szaimen
This is fixing a regression because the label we introduced was called "New" and is supposed to be that cause most actions in it are "New …".
> Fix "Add" label to "New"

- lib/upload.ts
- lib/uploader.ts
- package-lock.json
- package.json
Cannot upload to folder like `/dav/files/admin/Testing/New #folder/`
Works
> fix(uploader): encode destination

- l10n/messages.pot
- lib/components/UploadPicker.vue
* Resolves #1001 
All form elements - and this includes also the `progress` element - need a label this is now added.
Also semantically connecting the description with the progress by using `aria-describedby`
> fix(UploadPicker): Add label for upload progress and connect progress with description [a11y]

- lib/uploader.ts
Fix https://github.com/nextcloud-libraries/nextcloud-upload/issues/1032
> fix: also add `X-OC-Mtime` header to final chunks move

- lib/uploader.ts
Add proper cancellation
I investigated the quota check and ~~I will push~~ pushed a dedicated [backend fix on server](https://github.com/nextcloud/server/pull/42679)
| Before | After |
|:---------:|:------:|
|![2024-01-10_12-53](https://github.com/nextcloud-libraries/nextcloud-upload/assets/14975046/b55e38bb-c9c6-4a30-8908-59bcbe5d9edd)|![2024-01-10_12-53_1](https://github.com/nextcloud-libraries/nextcloud-upload/assets/14975046/2cefa0d8-9f42-4aaa-acc9-92026f6f0970)|
Fix https://github.com/nextcloud-libraries/nextcloud-upload/issues/2
> fix: properly handle chunk upload failure

- lib/uploader.ts
- lib/utils/upload.ts
* Resolves: https://github.com/nextcloud/server/issues/43335
For chunked uploads we have a progress after every finished chunk. But for non-chunked uploads we do not have any progress - even for big uploads.
To fix this I added the uploaded bytes to the upload progress of non-chunked uploads.
> fix: Add upload progress for non-chunked uploads

- package-lock.json
- package.json
- tsconfig.json
* There should be only one `Vue` version used in an application to make `Vue` a peer dependency
* TSConfig: `emitDeclarationOnly` is only valid if `noEmit` is set to `false`
* Update NPM version to 10 to support current LTS Node 20
> chore: Fix some issues with `package.json`

- CHANGELOG.md
- package.json
[Full Changelog](https://github.com/nextcloud-libraries/nextcloud-upload/compare/v1.0.4...v1.0.5)
* fix: also add `X-OC-Mtime` header to final chunks move by @skjnldsv in https://github.com/nextcloud-libraries/nextcloud-upload/pull/1038
* fix: properly handle chunk upload failure by @skjnldsv in https://github.com/nextcloud-libraries/nextcloud-upload/pull/1042
* fix: Add upload progress for non-chunked uploads by @susnux in https://github.com/nextcloud-libraries/nextcloud-upload/pull/1080
* fix: do not try to slice in chunk larger than the File itself by @skjnldsv in https://github.com/nextcloud-libraries/nextcloud-upload/pull/1057
* fix: Some issues with `package.json` by @susnux in https://github.com/nextcloud-libraries/nextcloud-upload/pull/1088
* Require NPM v10 to be compatible with …
> chore: Prepare 1.0.5

- cypress/components/ConflictPicker.cy.ts
- lib/components/ConflictPicker.vue
Resolves #1095
**Summary**
* Before, the ConflictPicker was built using NcModal. This is good, but migrating to NcDialog will allow for more features if needed in the future, and we also can remove the "x" button
* The reason this PR was opened was because we could not click it, but after looking more into it, I do not believe that the conflict picker should have it. Previously, it did not even close the modal anyways (it would open it again), and semantically, because a conflict is happening, I believe that the user should choose between a file, or ignore importing the file.
**Video**
https://github.com/nextcloud-libraries/nextcloud-upload/assets/110193237/0c1c5e86-ef57-44a1-bf9f-dc21e16a3ef1
> fix: migrate conflictpicker to NcDialog and remove incorrect semantic closing icon

- lib/uploader.ts
This allow us to not have to change the current uploader destination.
Needed for https://github.com/nextcloud/server/pull/44409
> feat: allow to specify the root of an upload

- cypress/components/UploadPicker.cy.ts
- cypress/cypress.d.ts
- cypress/support/commands.ts
- cypress/tsconfig.json
- lib/components/ConflictPicker.vue
- lib/components/UploadPicker.vue
> feat: allow to specify forbidden characters

- lib/components/NodesPicker.vue
- package-lock.json
- package.json
* Resolves #1149 
Moment.js is pretty heavy and also deprecated - not recommended for new projects. Instead we can use the functions from `@nextcloud/vue`
> fix: Drop dependency on moment.js

- lib/utils/upload.ts
- package-lock.json
- package.json
* Resolves: https://github.com/nextcloud/server/issues/43627
Instead of reading file chunks into memory and then upload those chunks, we should rather just slice the file and stream it for uploading. This prevents browsers to sky rocket the memory consumption.
We no longer need p-limit so drop that dependency.
---
You can test this by uploading a large file and monitor the process memory of your browser. Please note that Firefox has a browser bug: As long as the dev tools are open the request data is not freed so if you have the dev tools open you will still suffer this issue.
> fix(upload): Do not read chunks into memory but just stream file chunks

- lib/components/ConflictPicker.vue
- lib/index.ts
This is needed for folder upload support.
Fixes also some type errors like doing `[...NodeList]` which is not possible as NodeList does not implement iterators, so we need to use `Array.from`.
> feat(ConflictPicker): Allow to use `FileSystemEntry`

- lib/components/ConflictPicker.vue
- lib/components/NodesPicker.vue
- lib/utils/filesystem.ts
Some browsers do not support the API, but we still should support those browsers.
> fix(ConflictPicker): Ensure component works also if browser does not support FileSystemEntry

- README.md
- __tests__/tsconfig.json
- __tests__/utils/logger.spec.ts
- lib/utils/logger.ts
- package-lock.json
- package.json
- tsconfig.json
- vitest.config.ts
* Refactor the logger code - we no longer need to inject the user manually but can use the `detectUser` function
* Add a tiny test for the logger to ensure it works and sets the correct context
* Remove `utils/l10n.ts` from the code coverage - it makes no sense to test this
* Fixed links in README and badges
> fix: Refactor logger and fix badges in README

- __tests__/utils/filesystem.spec.ts
- lib/utils/filesystem.ts
Add missing unit tests and fix one typo.
> fix(tests): Add tests for filesystem helpers

- __tests__/setup.ts
- __tests__/utils/fileTree.spec.ts
- cypress/components/UploadPicker.cy.ts
- l10n/messages.pot
- lib/components/ConflictPicker.vue
- lib/components/UploadPicker.vue
- lib/index.ts
- lib/uploader.ts
- lib/utils/fileTree.ts
- lib/utils/uniqueName.ts
- package-lock.json
- package.json
- vitest.config.ts
* Part of https://github.com/nextcloud/server/issues/43238
* Design for uploader menu is taken from: https://github.com/nextcloud/server/issues/43728
Added a `Directory` class that allows creating a virtual filesystem.
Meaning the directory contains a tree of child nodes.
Then this tree is uploaded level by level within the uploader (new method `bulkUpload`).
The UploadPicker now also support directories when created with `allow-folders`.
---
> feat: Allow to upload directories and allow bulk upload

- CHANGELOG.md
- package-lock.json
- package.json
[Full Changelog](https://github.com/nextcloud-libraries/nextcloud-upload/compare/v1.1.1...v1.2.0)
* feat(NodesPicker): Add support for FileSystemEntry by @susnux in https://github.com/nextcloud-libraries/nextcloud-upload/pull/1165
* feat(ConflictPicker): Allow to use `FileSystemEntry` by @susnux in https://github.com/nextcloud-libraries/nextcloud-upload/pull/1166
* feat: Allow to upload directories and allow bulk upload by @susnux in https://github.com/nextcloud-libraries/nextcloud-upload/pull/1175
* feat: Split new-menu entries into `upload` `new` and *other* by @susnux in https://github.com/nextcloud-libraries/nextcloud-upload/pull/1206
* feat(ConflictPicker): refresh preview on etag change by @skjnldsv in https://github.com/nextcloud-libraries/nextcloud-upload/pull/1214
* …
> chore: Prepare v1.2.0 release

- CHANGELOG.md
- package-lock.json
- package.json
[Full Changelog](https://github.com/nextcloud-libraries/nextcloud-upload/compare/v1.2.0...v1.3.0)
* feat: Implement upload on public shares using dav endpoint v2 by @susnux in https://github.com/nextcloud-libraries/nextcloud-upload/pull/1225
* refactor: Only import from nextcloud-axios not axios directly by @susnux in https://github.com/nextcloud-libraries/nextcloud-upload/pull/1224
* chore(deps): Bump @nextcloud/files from 3.3.1 to 3.4.0 by @dependabot in https://github.com/nextcloud-libraries/nextcloud-upload/pull/1220
* chore(deps): Bump @types/node to 20.14.2 by @dependabot in https://github.com/nextcloud-libraries/nextcloud-upload/pull/1227
> chore: Prepare v1.3.0

- __tests__/utils/upload.spec.ts
- cypress.config.ts
- lib/uploader.ts
- lib/utils/upload.ts
- package-lock.json
- package.json
* Resolves https://github.com/nextcloud-libraries/nextcloud-upload/issues/5
You can observe how it works on the video below. I've tested library changes using `npm link`. For failure simulation I've added next snippet to `remote.php`:
```php
if ($_SERVER['REQUEST_METHOD'] === 'PUT' && random_int(0, 4) === 0) {
throw new RemoteException('Service unavailable', 503);
}
sleep(2);
```
Also as you can see sha256 hash is the same for the uploaded and original files. So, files are not corrupted during retries. Later on we can configure how many retries available.
https://github.com/nextcloud-libraries/nextcloud-upload/assets/191082/ddf6aa32-20eb-412f-89ee-08b8f9549962
> Added retry capability for uploading files

- CHANGELOG.md
- package-lock.json
- package.json
[Full Changelog](https://github.com/nextcloud-libraries/nextcloud-upload/compare/v1.3.0...v1.4.0)
* Added retry capability for uploading files [\#1233](https://github.com/nextcloud-libraries/nextcloud-upload/pull/1233) \([Koc](https://github.com/Koc)\)
* fix: Adjust `isPublic` detection for uploader [\#1234](https://github.com/nextcloud-libraries/nextcloud-upload/pull/1234) \([susnux](https://github.com/susnux)\)
* refactor: Use `getUniqueName` from `@nextcloud/files` [\#1244](https://github.com/nextcloud-libraries/nextcloud-upload/pull/1244) \([susnux](https://github.com/susnux)\)
* refactor: Use public-share aware functions from `@nextcloud/files` and `@nextcloud/sharing` [\#1245](https://github.com/nextcloud-libraries/nextcloud-upload/pull/1245) \([susnux](https://github.com/susnux)\) …
> chore: Prepare v1.4.0

- CHANGELOG.md
- package-lock.json
- package.json
* fix: Prevent issues with Chromium based browsers [\#1250](https://github.com/nextcloud-libraries/nextcloud-upload/pull/1250) \([susnux](https://github.com/susnux)\)
> chore: Prepare 1.4.1 release

- lib/components/UploadPicker.vue
Otherwise the files app displays the wrong entries twice 🙈
> fix: Use other menu entries instead of new ones twice

- cypress/components/UploadPicker.cy.ts
- lib/components/UploadPicker.vue
> feat: add cypress selectors for new menu entries

- lib/components/UploadPicker.vue
* Resolves https://github.com/nextcloud-libraries/nextcloud-upload/issues/1275
> fix(UploadPicker): Do not hardcode the height but use the CSS variable

- cypress/components/UploadPicker.cy.ts
- cypress/support/component-index.html
- lib/components/UploadPicker.vue
- package-lock.json
* Resolves https://github.com/nextcloud/server/issues/46875
We need to make sure we work with an up-to-date version of the current content, e.g. if a file was removed or added, so reload the current content on click.
The using app (esp. files) should have cached version so no requests are needed. (for files this is already the case).
When releasing this update and merging in server I will provide a cached "getContent" function (load from store if already known) to mitigate performance issues.
**edit** here it is: https://github.com/nextcloud/server/pull/46966
> fix: Always request current content when triggering a menu entry

- CHANGELOG.md
- package-lock.json
- package.json
* fix: Always request current content when triggering a menu entry by @susnux in https://github.com/nextcloud-libraries/nextcloud-upload/pull/1313
* fix: Remove outdated languages that are blocking the real translations by @susnux in https://github.com/nextcloud-libraries/nextcloud-upload/pull/1282
* fix(UploadPicker): Do not hardcode the height but use the CSS variable by @susnux in https://github.com/nextcloud-libraries/nextcloud-upload/pull/1309
* chore: Bump @nextcloud/files from 3.5.1 to 3.7.0 by @dependabot
* chore: Bump @nextcloud/paths from 2.1.0 to 2.2.1 by @dependabot
* chore: Bump @nextcloud/sharing from 0.2.2 to 0.2.3 by @dependabot
* chore: Bump @types/node from 20.14.10 to 22.1.0 by @dependabot
* chore: Bump @vitest/coverage-v8 from 2.0.2 to 2.0.5 by @dependabot
* chore: …
> chore: 1.4.3

- cypress/components/UploadPicker/UploadPicker.cy.ts
- lib/uploader.ts
* Resolve #1323 
Remove the hack with the concurrency of the job queue, instead refactor the directory creation:
1. Add it to the upload queue (to track progress)
2. Add the request to the job queue
3. Wait for parent to be created -> continue with children
Note that for demonstration purpose I limited the concurrency to **3** and throttled the network.
[Bildschirmaufnahme_20240813_165415.webm](https://github.com/user-attachments/assets/7d0985e8-e794-462c-a328-c88330b32eb2)
---
*Sorry for the big diff, but some refactoring needed to get rid of some of my hacks* :sweat_smile:
> fix(uploader): Make sure every request is added to the job queue

- CHANGELOG.md
- package-lock.json
- package.json
* feat(UploadPicker): Use `@nextcloud/files` filename validation by default [\#1310](https://github.com/nextcloud-libraries/nextcloud-upload/pull/1310) \([susnux](https://github.com/susnux)\)
* fix(uploader): Make sure every request is added to the job queue [\#1326](https://github.com/nextcloud-libraries/nextcloud-upload/pull/1326) \([susnux](https://github.com/susnux)\)
* chore: Bump @nextcloud/auth to 2.4.0
* chore: Bump @nextcloud/files to 3.8.0
* chore: Bump axios to 1.7.4
> chore: Prepare v1.5.0

- lib/uploader.ts
Make sure it is a valid timestamp (integer), so no decimals.
> fix(Uploader): The mtime should be a valid UNIX timestamp

- lib/uploader.ts
This some how breaks when used with Vue 2, maybe the prototype is not set correctly, but with the current files app this breaks.
So instead just validate the type if folder and a source is set (we only use the source).
> fix(uploader): validation of the destination should not compare the class

- cypress/components/UploadPicker/new-menu.cy.ts
- l10n/messages.pot
- lib/components/UploadPicker.vue
* :warning: This is chained onto https://github.com/nextcloud-libraries/nextcloud-upload/pull/1372
This allows to also use the upload picker without the menu for just uploading files / folders.
> feat(UploadPicker): Allow to disable the "new"-menu

- lib/index.ts
- lib/window.d.ts
This way it is possible e.g. for `files_sharing` and `files` to share the same uploader instance.
> fix: Make the default uploader global

- CHANGELOG.md
- package-lock.json
- package.json
* feat(uploader): Allow to specify custom headers [\#1366](https://github.com/nextcloud-libraries/nextcloud-upload/pull/1366) \([susnux](https://github.com/susnux)\)
* feat(UploadPicker): Allow to disable the "new"-menu [\#1373](https://github.com/nextcloud-libraries/nextcloud-upload/pull/1373) \([susnux](https://github.com/susnux)\)
* fix(Uploader): The mtime should be a valid UNIX timestamp [\#1368](https://github.com/nextcloud-libraries/nextcloud-upload/pull/1368) \([susnux](https://github.com/susnux)\)
* fix(uploader): validation of the destination should not compare the class [\#1369](https://github.com/nextcloud-libraries/nextcloud-upload/pull/1369) \([susnux](https://github.com/susnux)\)
* fix(UploadPicker): Show menu if folders are enabled …
> chore: Prepare v1.6.0

- __mocks__/@nextcloud/auth.js
- __mocks__/@nextcloud/router.js
- __tests__/uploader.spec.ts
- __tests__/utils/upload.spec.ts
- vitest.config.ts
Setup some global location within the setup, also use vmForks so CSS files are correctly mocked during tests. This allows to not inline nextcloud files so we can properly mock it if needed (e.g. for public share tests).
> test: Cleanup test setup

- __tests__/utils/conflicts.spec.ts
- lib/components/UploadPicker.vue
- lib/index.ts
- lib/utils/conflicts.ts
- lib/utils/dialog.ts
* Chained on #1441 
---
Move logic from upload picker into reusable utilities.
I think this helps by making the component smaller, thus better maintainable due to less complexity, and allowing to reuse the logic if needed (working on #617 ).
> feat: Add `uploadConflictHandler` to handle conflict resolution

- lib/uploader.ts
- package-lock.json
- package.json
https://github.com/nextcloud/server/issues/47682
https://github.com/nextcloud/server/pull/48758
> feat: Respect parallel count config

- __tests__/utils/fileTree.spec.ts
- lib/uploader.ts
- lib/utils/fileTree.ts
`addChild` is asynchronous and needs to be awaited, as `readEntries` is also async. This means it can not be done in the constructor but we need to handle this separately.
So instead just add a `addChildren` helper method and await this function where needed.
> fix: Fix adding children to directory (file tree) for batch uploading

- lib/uploader.ts
- lib/utils/upload.ts
Regression from https://github.com/nextcloud-libraries/nextcloud-upload/pull/1175
Fix for https://github.com/nextcloud/server/issues/49287
- When uploading with the upload method (not batchUpload), the jobQueue gets idle before the chunks gets computed and between the chunk upload and the final assembly.
- Unfortunately, resetting clear the entirety of the uploadQueue
- This makes the UI looks like there is no pending upload despite more requests being added to the stack afterwards
This is a fix, but we could definitely improve here again, with the batchUpload method, things got messy.
But this would be technical debt, and the bug that this PR fixes is critical.
By moving the idle listener to the end of the method, we are ensuring that the upload's job queue is fully populated before the …
> fix(uploader): only monitor the queue being idle when we kow we are finishing the upload

- cypress/components/UploadPicker/UploadPicker.cy.ts
- cypress/components/UploadPicker/hotkeys.cy.ts
- cypress/components/UploadPicker/new-menu.cy.ts
- cypress/support/component.ts
- lib/components/UploadPicker.vue
- lib/index.ts
- lib/uploader.ts
- lib/utils/upload.ts
Subset of https://github.com/nextcloud/server/issues/30484
Follow-up of https://github.com/nextcloud/server/pull/49432
> feat: add upload menu shortcuts 

- lib/components/NodesPicker.vue
The server generates the preview using cover mode, so the local preview of the new file should do the same.
Also the preview was always distorted, I believe this was due to background-size not applying to the image.
To fix this I had to use object-fit instead.
Before:
After:
> fix(NodesPicker): Use preview fit cover

- CHANGELOG.md
- package-lock.json
- package.json
* feat: add upload menu shortcuts [\#1529](https://github.com/nextcloud-libraries/nextcloud-upload/pull/1529) \([skjnldsv](https://github.com/skjnldsv)\)
* fix(NodesPicker): Use preview fit cover [\#1548](https://github.com/nextcloud-libraries/nextcloud-upload/pull/1548) \([provokateurin](https://github.com/provokateurin)\)
* Updated development dependencies
* chore(deps): bump nanoid to 3.3.8 [\#1523](https://github.com/nextcloud-libraries/nextcloud-upload/pull/1523)
* chore(deps): bump @nextcloud/files to 3.10.1 [\#1527](https://github.com/nextcloud-libraries/nextcloud-upload/pull/1527)
> chore: Prepare v1.8.0 release

- .env.development
- REUSE.toml
Vue devtools will be removed / disabled if `NODE_ENV=production` which is the default.
To enable it we need to explicitly set it (vite mode and `NODE_ENV` are two distinct things).
> chore: include vue devtools in dev build

- __tests__/utils/upload.spec.ts
- cypress/components/UploadPicker/progress.cy.ts
- lib/components/UploadPicker.vue
- lib/uploader.ts
- lib/utils/upload.ts
On upload event we should also update the uploaded bytes for chunked uploads.
Moreover we need to reset the uploaded bytes when a retry occures as the progress bar is otherwise showing the wrong ETA.
Basically:
- on progress event: Update the uploaded bytes to 90% of it (we reserve 10% until the request finished)
- on response we add that 10% reserved bytes (so the server responded with OK -> mark the chunk / upload as 100% done)
- on retry we reset the uploaded bytes for that chunk
> fix(uploader): Correctly (re)set progress on upload

- lib/components/UploadPicker.vue
Required for https://github.com/nextcloud/server/issues/48527
> feat(UploadPicker): Allow to set color to primary

- cypress/components/UploadPicker/cancel.cy.ts
- l10n/messages.pot
- lib/components/UploadPicker.vue
- lib/errors/UploadCancelledError.ts
- lib/uploader.ts
* Closes https://github.com/nextcloud-libraries/nextcloud-upload/pull/1614
* Resolves https://github.com/nextcloud-libraries/nextcloud-upload/issues/1543
To reproduce:
1. Upload a file which already exists
2. Cancel
3. See the progress still visible
4. See error saying something went wrong (but it didn't, the user cancelled on purpose)
> fix(uploader): properly propagate upload cancelled status

- cypress/components/UploadPicker/UploadPicker.cy.ts
- cypress/components/UploadPicker/progress.cy.ts
- cypress/components/UploadPicker/status.cy.ts
- cypress/support/component.ts
- l10n/messages.pot
- lib/components/UploadPicker.vue
- lib/uploader.ts
@Koc here is my take on this.
I think adding some text to the right isn't the right approach.
Now we make sure we don't have any ongoing upload that are NOT assembling
If all is left is assembling tasks, we show the status.
Closes https://github.com/nextcloud-libraries/nextcloud-upload/pull/1458
> feat: add assembling status to UploadPicker

- cypress/components/UploadPicker/UploadPicker.cy.ts
- cypress/components/UploadPicker/invalid-filenames.cy.ts
- cypress/components/UploadPicker/progress.cy.ts
- cypress/cypress.d.ts
- cypress/support/commands.ts
- lib/components/UploadPicker.vue
- lib/index.ts
- lib/uploader/eta.spec.ts
- lib/uploader/eta.ts
- lib/uploader/index.ts
- lib/uploader/uploader.ts
- package-lock.json
- package.json
* Resolves #1605 
* Party for #816 
This feature implements the following:
- Implement the ETA class our self
- Provide upload speed information in the ETA class
- Move the ETA information to the uploader class
- Remove custom ETA from uploader component and add uploading speed.
Due to the risks of something breaking this is **100%** test covered (unit tests) and additionally added component tests for it.
> feat(uploader): add ETA implementation with upload speed information

- CHANGELOG.md
- package-lock.json
- package.json
* feat: add assembling status to UploadPicker by @skjnldsv in https://github.com/nextcloud-libraries/nextcloud-upload/pull/1530
* feat(UploadPicker): Allow to set color to primary by @susnux in https://github.com/nextcloud-libraries/nextcloud-upload/pull/1606
* feat(uploader): add ETA implementation with upload speed information by @susnux in https://github.com/nextcloud-libraries/nextcloud-upload/pull/1627
* fix: fix eslint scripts by @Koc in https://github.com/nextcloud-libraries/nextcloud-upload/pull/1518
* fix: include non conflicting files for upload by @susnux in https://github.com/nextcloud-libraries/nextcloud-upload/pull/1615
* fix(conflictpicker): force background on sticky header by @skjnldsv in https://github.com/nextcloud-libraries/nextcloud-upload/pull/1635
* fix(uploader): …
> chore: 1.9.0

- __tests__/utils/upload.spec.ts
- cypress/components/UploadPicker/retry.cy.ts
- lib/utils/upload.ts
1. locked is temporary - often because of preview generation.
2. insufficient storage is permanent we should not retry and make the upload take very long to finally fail.
> fix(upload): do not retry when insufficient storage but when locked

- lib/uploader/uploader.ts
* Resolves https://github.com/nextcloud/server/issues/50889
Fixes a problem with Android devices that have NT epoch set on the file system (e.g. NTFS / FAT SD cards). Those files will report a negative modification time.
> fix(uploader): only set mtime if valid value is passed

- CHANGELOG.md
- package-lock.json
- package.json
* fix(upload): do not retry when insufficient storage but when locked [\#1657](https://github.com/nextcloud-libraries/nextcloud-upload/pull/1657) \([susnux](https://github.com/susnux)\)
* fix(uploader): only set mtime if valid value is passed [\#1666](https://github.com/nextcloud-libraries/nextcloud-upload/pull/1666) \([susnux](https://github.com/susnux)\)
* Updated Axios to version 1.8.3
* Updated development dependencies
* chore(i18n): adding hint for translators [\#1643](https://github.com/nextcloud-libraries/nextcloud-upload/pull/1643) \([rakekniven](https://github.com/rakekniven)\)
* chore(i18n): Fixes wrong translations syntax [\#1645](https://github.com/nextcloud-libraries/nextcloud-upload/pull/1645) \([rakekniven](https://github.com/rakekniven)\)
> chore: prepare release of v1.9.1

- lib/uploader/uploader.ts
- lib/utils/upload.ts
https://github.com/nextcloud/server/issues/4109
https://github.com/nextcloud/server/pull/52182
> feat(Uploader): Enable chunked upload for public shares if supported
